// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdvbamludxdghpsxuurl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkdmJhbWx1ZHhkZ2hwc3h1dXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MTY4NjcsImV4cCI6MjA2MjQ5Mjg2N30.2oeHlnoC4-harNVjCzP9li93tbBjVIuqz-Oiaok3p7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);